# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: clang-tidy
      - task: clang-format

  format:
    cmds:
      - task: clang-format

  clang-format:
    silent: true
    sources:
      - src/**/*.c
      - src/**/*.h
    cmds:
      - for: sources
        cmd: |
          clang-format -i "{{joinPath .TASKFILE_DIR .ITEM}}"

  clang-tidy:
    silent: true
    sources:
      - src/**/*.c
      - src/**/*.h
    cmds:
      - for: sources
        cmd: |
          clang-tidy "{{joinPath .TASKFILE_DIR .ITEM}}" \
            --config-file="{{joinPath .TASKFILE_DIR ".clang-tidy"}}" \
            --use-color \
            --fix \
            --fix-notes \
            --fix-errors
