# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: clang-format

  clang-format:
    silent: true
    sources:
      - src/**/*.c
      - src/**/*.h
    cmds:
      - for: sources
        cmd: |
          clang-format -i "{{joinPath .TASKFILE_DIR .ITEM}}"

  clang-tidy:
    silent: true
    sources:
      - src/**/*.c
      - src/**/*.h
    cmds:
      - for: sources
        cmd: |
          clang-tidy "{{joinPath .TASKFILE_DIR .ITEM}}" \
            -fix \
            -fix-errors \
            -checks="readability-braces-around-statements"
